// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb4FH5HItIfHtjXf48QAvdVa-XCwN-KJY',
    appId: '1:40630012429:web:0fd474e1c564fa6e872344',
    messagingSenderId: '40630012429',
    projectId: 'shiftsync-417b1',
    authDomain: 'shiftsync-417b1.firebaseapp.com',
    storageBucket: 'shiftsync-417b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh2H2Ai1FLD7SH74-sIX2XKOiv_z8B0Uo',
    appId: '1:40630012429:android:eb8f758f8e94a922872344',
    messagingSenderId: '40630012429',
    projectId: 'shiftsync-417b1',
    storageBucket: 'shiftsync-417b1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb4FH5HItIfHtjXf48QAvdVa-XCwN-KJY',
    appId: '1:40630012429:web:0fd474e1c564fa6e872344',
    messagingSenderId: '40630012429',
    projectId: 'shiftsync-417b1',
    authDomain: 'shiftsync-417b1.firebaseapp.com',
    storageBucket: 'shiftsync-417b1.firebasestorage.app',
  );
}
